### ISSUE TITLE
Does evSeq support WSL?

### ISSUE THREAD

**Issue by YTMiiikey** [fhalab/evSeq#36]
Hi everyone,

I am trying install evSeq on my windows computer within its WSL2 (Windows Subsystem for Linux). I keep getting errors associated with gtk+, a package seemingly related to GUI. I wonder if evSeq is supposed to support WSL? Is there a way to install a GUI-free version of evSeq? Thank you so much in advance!

Tian

**Comment by brucejwittmann** [comment]
Hi Tian,

We've never explicitly tested evSeq on WSL2, but there's no reason to think it wouldn't work. I have come across issues with gtk+ when installing evSeq on Linux before that seem to match your problem. Check out the last entry of our troubleshooting section on the wiki (bottom of the page linked [here](https://fhalab.github.io/evSeq/9-troubleshooting.html)) and see if that helps resolve the problem. 

A GUI-free version is something that we've been wanting to put together for a while. We haven't gotten around to it yet, though. Let us know if you can't solve the problem with the troubleshooting guide and that will probably give us a kick to get around to doing it.

**Comment by YTMiiikey** [comment]
Hi Bruce,

It worked after I installed gtk+ following the troubleshooting guide. Thanks so much for your prompt response! I'm looking forward to see my result haha.

**Comment by brucejwittmann** [comment]
Great! Glad you got it working. Please let us know if you run into any other issues. Excited to hear that you're using evSeq!
